# Generated by Django 5.0.6 on 2024-06-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_info',
        ),
    ]
