# Generated by Django 5.0.6 on 2024-06-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
